# Generated by Django 6.0.2 on 2026-02-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teachersubject",
            name="section",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="section",
        ),
        migrations.AlterUniqueTogether(
            name="studentsubject",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="studentsubject",
            name="student",
        ),
        migrations.RemoveField(
            model_name="studentsubject",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="teachersubject",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="teachersubject",
            name="teacher",
        ),
        migrations.AlterField(
            model_name="users",
            name="Role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("employee", "Employee"),
                    ("user", "Member"),
                ],
                default="user",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Attendance",
        ),
        migrations.DeleteModel(
            name="Section",
        ),
        migrations.DeleteModel(
            name="StudentSubject",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
        migrations.DeleteModel(
            name="TeacherSubject",
        ),
    ]
