# Generated by Django 6.0.2 on 2026-02-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_teachersubject_section_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="token_version",
            field=models.IntegerField(default=0),
        ),
    ]
