# Generated by Django 5.2.11 on 2026-08-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_users_last_logout_alter_users_role_passwordresetotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="citizenship_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="users",
            name="pan_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="Role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("organizer", "Organizer"),
                    ("citizen", "Citizen"),
                ],
                default="citizen",
                max_length=20,
            ),
        ),
    ]
