# Generated by Django 6.0.8 on 2026-09-18 05:07

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_users_citizenship_number_users_pan_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="Role",
        ),
        migrations.RemoveField(
            model_name="users",
            name="pan_number",
        ),
        migrations.AddField(
            model_name="users",
            name="pharmacy_license_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="RegistrationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("username", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[("patient", "Patient"), ("pharmacy", "Pharmacy")],
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("password", models.CharField(max_length=128)),
                (
                    "citizenship_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "citizenship_front",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.registration_upload_path,
                    ),
                ),
                (
                    "citizenship_back",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.registration_upload_path,
                    ),
                ),
                (
                    "pharmacy_license_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "pharmacy_license_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.registration_upload_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("pharmacy", "Pharmacy"),
                    ("patient", "Patient"),
                ],
                default="patient",
                max_length=20,
            ),
        ),
    ]
