# Generated by Django 6.0.8 on 2026-09-18 06:05

import django.db.models.deletion
import django.utils.timezone
import reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                ("short_description", models.TextField(blank=True, null=True)),
                ("mg", models.CharField(max_length=50)),
                (
                    "medicine_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=reports.models.medicine_photo_path,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pharmacy",
                    models.ForeignKey(
                        limit_choices_to={"role": "pharmacy"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicineOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mg", models.CharField(max_length=50)),
                (
                    "prescription_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=reports.models.prescription_photo_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("delivered", "Delivered"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("denial_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="reports.medicine",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"role": "patient"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicine_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        limit_choices_to={"role": "pharmacy"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
