# Generated by Django 6.0.8 on 2026-09-18 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medicine",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="medicineorder",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="medicine",
            name="available_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="medicineorder",
            name="delivery_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicineorder",
            name="delivery_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="medicineorder",
            name="delivery_location_accuracy",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="medicineorder",
            name="delivery_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="medicineorder",
            name="delivery_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicineorder",
            name="location_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicineorder",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="pharmacy",
            field=models.ForeignKey(
                limit_choices_to={"Role": "pharmacy"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="medicineorder",
            name="patient",
            field=models.ForeignKey(
                limit_choices_to={"Role": "patient"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicine_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="medicineorder",
            name="pharmacy",
            field=models.ForeignKey(
                limit_choices_to={"Role": "pharmacy"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pharmacy_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
