# Generated by Django 6.0.8 on 2026-09-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_medicine_pharmacy_alter_medicineorder_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorder',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
