# Generated by Django 6.0.8 on 2026-09-18 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_medicineorder_contact_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pharmacy',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'pharmacy'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
