"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-u*j9$6=_j0m60jx$fr+@n9zue)n+a4j4tqp6%=qllqfh#5_una"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",

    "rest_framework",
    "chatbot.apps.ChatbotConfig",
    
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",

    "https://cfcf-182-93-68-229.ngrok-free.app",

    # Vercel frontend
    "https://react-frontend-tvl2.vercel.app",

    # Render backend/frontend if applicable
    "https://drf-1-p3vn.onrender.com",

    # VS Code dev tunnel
    "https://sm3j0j49-5173.inc1.devtunnels.ms",
    "https://ns7s5p47-5173.inc1.devtunnels.ms",
]
import os
from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    "ngrok-skip-browser-warning",
]

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "ai_cache",
        "TIMEOUT": 3 * 60 * 60,
    }
}
SEMANTIC_CACHE_EMBEDDING_MODEL = (
    "sentence-transformers/all-MiniLM-L6-v2"
)
SEMANTIC_CACHE_SIMILARITY_THRESHOLD = 0.88

SEMANTIC_CACHE_TTL = 60 * 60 * 24

SEMANTIC_CACHE_MAX_ENTRIES = 5000
# ------------------------------------------------------------
# AI ANSWER CACHE TTLs (seconds)
#
# Read by cache_utils.get_general_cache_ttl() / get_rag_cache_ttl()
# — this is the ONE place these are configured; nothing else in
# the codebase should hardcode a TTL number. Override via
# environment variables in prod without touching code.
# ------------------------------------------------------------
 
GENERAL_ANSWER_CACHE_TTL = int(
    os.getenv("GENERAL_ANSWER_CACHE_TTL", 60 * 60 * 24)  # 24 hours
)
 
RAG_ANSWER_CACHE_TTL = int(
    os.getenv("RAG_ANSWER_CACHE_TTL", 60 * 60 * 3)  # 3 hours
)



# =========================================================
# CSRF
# =========================================================

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",

    "https://react-frontend-tvl2.vercel.app",

    "https://sm3j0j49-5173.inc1.devtunnels.ms",

    "https://drf-1-p3vn.onrender.com",

    # ngrok
    "https://*.ngrok-free.app",
]
import os

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.smtp.EmailBackend",
        "OPTIONS": {
            "host": "smtp.gmail.com",
            "port": 587,
            "username": "katuwalmadan55@gmail.com",
            "password": "lrsa giqa ylhc qgro",
            "use_tls": True,
            "timeout": 20,
        },
    },
}
DEFAULT_FROM_EMAIL = "Medikart <katuwalmadan55@gmail.com>"

INTERNAL_API_KEY = "crURdE1AZq_2-cs5Y8G_J8aSd_lGuMF5kqFqDLBi84M"
